### PR TITLE
Updates CaliperNativeReader to support all Caliper data types

### PR DESCRIPTION
**Pull request by ilumsden**
While working on some benchmarking for the El Capitan EAS Rabbit nodes, I discovered that Hatchet's `CaliperNativeReader` could not support the custom `data_size` attribute I had created in Caliper. The reason for this is that Hatchet does not support all of Caliper's data types. The bullet list below shows which types Hatchet does and does not support:
* Supports:
  * `double`
  * `int`
  * `string`
* Doesn't Support:
  * `inv`
  * `usr`
  * `uint`
  * `addr`
  * `bool`
  * `type`
  * `ptr`

This PR adds the ability to support all the Caliper types above. It does this by introducing a private dictionary to `CaliperNativeReader` called `__cali_type_dict`. This dictionary uses Caliper type names (from `caliperreader`) as keys and unary functions as values. The unary functions are either type constructors (e.g., `int()`, `str()`) or lambdas that raise `ValueError`s.

This dictionary is used in `read_metrics` (specifically the `for` loop starting on line 109). Using the dictionary, we no longer have to manually check for types with multiple if-elif statements. Instead, we simply do the following:
* Check if the Caliper attribute type is in the set of dictionary keys
* Check if the Caliper attribute is supposed to be collected (i.e., preserves the existing functionality associated with the `string_attributes` parameter)
* Tries to obtain a Python type from Caliper using the corresponding value from `__cali_type_dict`. This will either succeed or produce a `ValueError`
* Catch any `ValueError`s. If the attribute has a Caliper `inv` or `ptr` type (meant to be for internal use only), the error is re-raised. Otherwise, a message is printed informing the user that the attribute has been skipped.

### CODE REVIEW

**Comment by slabasan** [comment]
@ilumsden Looks good, can you rebase this when you get a chance?

**Comment by ilumsden** [comment]
@slabasan just rebased

**Comment by ilumsden** [comment]
Looks like this PR breaks some of the Caliper tests due to data types on the Python side. So, I've got a few more things that have got to be modified.

**Comment by slabasan** [comment]
Closing this in favor of #107

**Pull request closed without merging**
